### ISSUE TITLE
xctool: command not found

### ISSUE THREAD

**Issue by joshbuchea** [pressly/react-native-nurse#1]
My first attempt using this script failed due to a missing dependency: [xctool](https://github.com/facebook/xctool).

`/usr/local/bin/nurse: line 110: xctool: command not found`

To resolve this issue, install [xctool](https://github.com/facebook/xctool):

`brew install xctool`

I updated the README to include [xctool](https://github.com/facebook/xctool) and submitted a pull request.

**Comment by alinz** [comment]
@joshbuchea thanks for this.
